[package]
name = "egui-euc"
version = "0.1.0"
edition = "2024"

[dependencies]
euc = { git = "https://github.com/zesterer/euc.git", rev = "e8f7aee" }
egui = "0.32.0"
#egui-winit = { version = "0.32.0", default-features = false, features = ["links"] }

[dev-dependencies]
pixels = "0.15.0"
env_logger = "0.10"
error-iter = "0.4"
log = "0.4"
winit = "0.29"
winit_input_helper = "0.15"
